---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{values.name | dump}}
  description: SD model
  annotations:
    backstage.io/kubernetes-label-selector: 'entity-id=${{values.name}}'
    backstage.io/kubernetes-namespace: ${{values.namespace}}
    argocd/app-name: ${{values.name | dump}}
  links:
    - url: 'github.com?owner=omrishiv-cnoe-test&repo=${{values.namespace}}-${{values.name}}'
      title: Repo URL
      icon: github
spec:
  owner: guest
  lifecycle: experimental
  type: service