---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{values.name | dump}}
  description: llama model
  annotations:
    backstage.io/kubernetes-label-selector: 'entity-id=${{values.name}}'
    backstage.io/kubernetes-namespace: ${{values.namespace}}
    argocd/app-name: ${{values.name | dump}}
  links:
    - url:  ${{parameters.repoUrl}}
      title: Repo URL
      icon: github
spec:
  owner: guest
  lifecycle: experimental
  type: service