---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "${{values.name}}-${{values.namespace}}"
  description: llama model
  annotations:
    backstage.io/kubernetes-label-selector: 'entity-id=${{values.name}}-${{values.namespace}}'
    backstage.io/kubernetes-namespace: ${{values.namespace}}
    argocd/app-name: ${{values.name | dump}}
  links:
    - url:  'https://github.com/omrishiv-cnoe-test/${{values.name}}-${{values.namespace}}'
      title: Repo URL
      icon: github
    - url:  'https://${{values.name}}-${{values.namespace}}.arcadeai.site/'
      title: Ray Dashboard
      icon: dashboard
    - url:  'https://grafana.arcadeai.site/d/2LaqbJ0Zk/kubecost?orgId=1var-namespace=${{values.namespace}}&var-app=${{values.name}}-${{values.namespace}}'
      title: Cost Dashboard
      icon: dashboard
    - url: 'https://grafana.arcadeai.site/d/rayServeDashboard/serve-dashboard?orgId=1&var-datasource=prometheus&var-Application=llama2'
      title: Serving Dashboard
      icon: dashboard
    - url: 'https://grafana.arcadeai.site/d/rayServeDeploymentDashboard/serve-deployment-dashboard?orgId=1&var-datasource=prometheus&var-Application=llama2'
      title: Serving Deployment Dashboard
      icon: dashboard
spec:
  owner: guest
  lifecycle: experimental
  type: service
  providesApis:
    - "${{values.name}}-${{values.namespace}}"
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: "${{values.name}}-${{values.namespace}}"
  description: The Llama API
spec:
  type: openapi
  lifecycle: experimental
  owner: guest
  definition:
    $text: ./llama.oas.yaml
